---
- name: Add multiple users
  hosts: all
  become: true
  tasks:
    - name: Ensure users exist
      user:
        name: "{{ item }}"
        state: present
        groups: sudo
      loop:
        - john
        - sarah
        - michelle
        - michael

